apiVersion: apps/v1
kind: Deployment
metadata:
  name: finsight-app
  labels:
    app: finsight-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: finsight-app
  template:
    metadata:
      labels:
        app: finsight-app
    spec:
      containers:
      - name: finsight-app
        image: ${DOCKER_REGISTRY}/finsight-app:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: finsight-app-service
spec:
  selector:
    app: finsight-app
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: finsight-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: finsight.example.com  # Replace with your actual domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: finsight-app-service
            port:
              number: 80